#!/usr/bin/env python3
"""Zero-config production deployment generator for Semantic Engine.

Generates high-entropy cryptographic secrets, configures `.env.prod`,
and validates the production Docker Compose topology.
"""

import argparse
from pathlib import Path
import secrets
import subprocess
import sys


def generate_production_env(output_path: Path, force: bool = False) -> bool:
    if output_path.exists() and not force:
        print(f"[!] Production env file already exists at: {output_path}")
        print("    Use --force to overwrite and rotate all production credentials.")
        return False

    qdrant_key = secrets.token_hex(24)
    redis_password = secrets.token_hex(24)
    admin_key = secrets.token_hex(32)

    content = f"""# ==============================================================================
# Semantic Engine Live Production Configuration
# Auto-generated by scripts/deploy_production.py
# ==============================================================================

DEBUG=false
GATEWAY_ADMIN_KEY={admin_key}
QDRANT_API_KEY={qdrant_key}
REDIS_PASSWORD={redis_password}
OLLAMA_MODEL=llama3.2

GATEWAY_BIND_IP=127.0.0.1
PORTAL_BIND_IP=127.0.0.1
CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
NEXT_PUBLIC_API_URL=http://localhost:8000
"""
    output_path.write_text(content, encoding="utf-8")
    print(f"[OK] Generated secure production configuration at: {output_path}")
    print(f"     Gateway Master Admin Key: {admin_key}")
    return True


def validate_compose(compose_file: Path, env_file: Path) -> bool:
    cmd = [
        "docker",
        "compose",
        "-f",
        str(compose_file),
        "--env-file",
        str(env_file),
        "config",
        "--quiet",
    ]
    try:
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode == 0:
            print("[OK] Docker Compose production topology validated successfully.")
            return True
        else:
            print(f"[!] Compose validation failed:\n{res.stderr}")
            return False
    except FileNotFoundError:
        print("[INFO] Docker binary not found in current PATH. Skipping live compose validation.")
        return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Deploy Semantic Engine Production Stack")
    parser.add_argument("--force", action="store_true", help="Force overwrite of existing .env.prod")
    parser.add_argument("--check-only", action="store_true", help="Only validate existing configuration")
    args = parser.parse_args()

    root_dir = Path(__file__).resolve().parent.parent
    prod_env = root_dir / ".env.prod"
    compose_file = root_dir / "docker-compose.prod.yml"

    if not args.check_only:
        generate_production_env(prod_env, force=args.force)

    if prod_env.exists():
        validate_compose(compose_file, prod_env)
        print("\n" + "=" * 70)
        print("Ready to deploy Semantic Engine in Production!")
        print("To launch all services (Gateway, Portal, Qdrant, Redis, Ollama):")
        print("-> docker compose -f docker-compose.prod.yml --env-file .env.prod up -d --build")
        print("=" * 70)
        return 0
    else:
        print("[!] Missing .env.prod. Run without --check-only to generate.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
