"""Rotate local SES secrets without printing secret material.

The generated files are intentionally ignored by Git:
- .env stores the local Gateway administrator API key.

Production deployments should inject the equivalent value through their secret
manager instead of copying this local file.
"""

from __future__ import annotations

import hashlib
import os
import secrets
import sqlite3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"
SQLITE_GATEWAY_PATH = ROOT / "data" / "gateway.db"
LEGACY_GATEWAY_ADMIN_KEY = "ses_dev_secret_key"
DEFAULT_CORS_ORIGINS = (
    "http://127.0.0.1:8000,http://localhost:8000,http://localhost:3000"
)


def _replace_env_value(lines: list[str], name: str, value: str) -> list[str]:
    prefix = f"{name}="
    replaced = False
    output: list[str] = []
    for line in lines:
        if line.startswith(prefix):
            output.append(f"{prefix}{value}")
            replaced = True
        else:
            output.append(line)
    if not replaced:
        output.append(f"{prefix}{value}")
    return output


def rotate_gateway_admin_key():
    admin_key = "ses_" + secrets.token_hex(24)
    previous_admin_key = None
    if ENV_PATH.exists():
        lines = ENV_PATH.read_text(encoding="utf-8").splitlines()
        for line in lines:
            if line.startswith("GATEWAY_ADMIN_KEY="):
                previous_admin_key = line.split("=", 1)[1].strip() or None
                break
    else:
        lines = [
            "# Local-only SES configuration generated by rotate_local_secrets.py",
            "DEBUG=true",
            f"GATEWAY_CORS_ORIGINS={DEFAULT_CORS_ORIGINS}",
        ]
    lines = _replace_env_value(lines, "GATEWAY_ADMIN_KEY", admin_key)
    ENV_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    os.chmod(ENV_PATH, 0o600)
    return previous_admin_key


def revoke_local_sqlite_keys(raw_keys) -> int:
    if not SQLITE_GATEWAY_PATH.exists():
        return 0
    key_hashes = [
        (hashlib.sha256(raw_key.encode()).hexdigest(),)
        for raw_key in raw_keys
        if raw_key
    ]
    revoked = 0
    with sqlite3.connect(SQLITE_GATEWAY_PATH) as connection:
        cursor = connection.executemany(
            "UPDATE api_keys SET status = 'revoked' WHERE key_hash = ? AND status != 'revoked'",
            key_hashes,
        )
        revoked = cursor.rowcount
        connection.commit()
    return revoked


def main() -> None:
    previous_admin_key = rotate_gateway_admin_key()
    revoked_count = revoke_local_sqlite_keys(
        [LEGACY_GATEWAY_ADMIN_KEY, previous_admin_key]
    )
    print(f"Rotated local Gateway administrator key in {ENV_PATH.name}.")
    print(f"Revoked local SQLite administrator keys: {revoked_count}.")
    print("Secret values were not printed.")
    print("Restart the Gateway after rotation so the new administrator key is bootstrapped.")


if __name__ == "__main__":
    main()
